version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: kafkadocker_kafka
    ports:
      - "9092:9092"
      - "8778:8778"
    environment:
      - KAFKA_OPTS=-javaagent:/opt/kafka/libs/jolokia-jvm-1.3.6-agent.jar
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.6
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_KAFKA_OPTS: "-javaagent:/opt/kafka/libs/jolokia-jvm-1.3.6-agent.jar"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
