version: '3'
services:
  elasticsearch:
    image: elasticsearch:2.4.0
    ports:
      - "9200:9200"
    networks:
      - monitoring
    environment:
      - ES_JAVA_OPTS=-Dmapper.allow_dots_in_name=true
    deploy:
      replicas: 1
  kibana:
    image: kibana:4.6.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - monitoring
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      replicas: 1
networks:
  monitoring:
