version: "3"
services:
  web:
    image: dironman/order-intake-svc:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname == ${KNODE_IP_ADDRESS}"
    volumes:
      - "/tmp:/logs"
    networks:
      - orderapp
      - kafka_kafkacluster
    environment:
      - KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - ZOOKEEPER_ADDRESS=${ZOOKEEPER_ADDRESS}
  order_processing:
    image: dironman/order-processing-svc:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname == ${KNODE_IP_ADDRESS}"
    environment:
      - KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - ZOOKEEPER_ADDRESS=${ZOOKEEPER_ADDRESS}
    networks:
      - orderapp
      - kafka_kafkacluster
  orderappls:
    image: logstash
    command: -f /config-dir/spring-boot-ls.conf
    deploy:
      mode: global
    volumes:
      - $PWD/:/config-dir
      - /tmp:/logs
    networks:
      - monitors_monitoring
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "11400:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - orderapp
      - kafka_kafkacluster
      - monitors_monitoring
networks:
  orderapp:
  kafka_kafkacluster:
    external: true
  monitors_monitoring:
    external: true
