version: '3'
services:
  swarmmetrics:
    image: djenriquez/sherpa
    ports:
      - "4550:4550"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    command: --allow
    networks:
      - swarmnet
  swarmmetricagg:
    image: logstash
    command: -f /config-dir/swarm-metric-agg-ls.conf
    deploy:
      replicas: 1
    depends_on:
      - swarmmetrics
    volumes:
      - $PWD:/config-dir
    networks:
      - swarmnet
      - monitors_monitoring
  cadvisor:
    image: google/cadvisor:latest
    command: -storage_driver=elasticsearch -storage_driver_es_host="http://elasticsearch:9200"
    deploy:
      mode: global
    depends_on:
      - swarmmetrics
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
    networks:
      - swarmnet
      - monitors_monitoring
networks:
  swarmnet:
  monitors_monitoring:
    external: true
